### ISSUE TITLE
Github action for creating SARIF reports	

### ISSUE THREAD

**Issue by alexeyfridman** [UnitTestBot/UTBotJava#124]
SAT-1627

**Comment by IdeaSeeker** [comment]
https://github.com/UnitTestBot/UTBotJava-action

Gradle plugin should be applied to the project:
https://plugins.gradle.org/plugin/org.utbot.gradle.plugin

Example of a workflow:

```YAML
name: "Run UTBotJava-action"

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 8

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 6.8

    - name: Run UTBotJava-action
      uses: UnitTestBot/UTBotJava-action@main
```
