### ISSUE TITLE
Use appropriate database settings for Spring integration tests generation

### ISSUE THREAD

**Issue by EgorkaKulikov** [UnitTestBot/UTBotJava#2220]
**Description**

Consider generating integration tests for Spring project.
Concrete execution is used, it requires to establish database connection for many projects

Concrete database settings must be the following (h2 in-memory database is used):

```
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true
```
