### ISSUE TITLE
Make the UTBot-action configurable

### ISSUE THREAD

**Issue by IdeaSeeker** [UnitTestBot/UTBotJava#315]
**Description**

The user should be able to configure the UTBot-action from their workflow file.
To do this, the `generateTestsAndSarifReport` task should handle "-P" parameters.

**Expected behavior**

The user writes:

```YAML
- name: Run UTBotJava-action
  uses: UnitTestBot/UTBotJava-action@main
  with:
    github_token: ...
    pushTests: 'true'
    targetClasses: '[ ... ]'
    generatedTestsRelativeRoot: '.utbot/test'
    testFramework: 'junit5'
    mockFramework: 'mockito'
    generationTimeout: '10000' # ms
    codegenLanguage: 'java'
    mockStrategy: 'do-not-mock'
    staticsMocking: 'do-not-mock-statics'
    forceStaticMocking: 'force'
    classesToMockAlways: '[ ... ]'
```

And all the specified parameters will be passed to the `generateTestsAndSarifReport` task.

**Context**

UTBotJava-action is the GitHub action for generating tests and creating SARIF reports based on UTBotJava. It uses `utbot-gradle` plugin to run test generation.
